_types: &types
  - type: feat
    section: 'Features'
  - type: fix
    section: 'Bug Fixes'
  - type: docs
    section: 'Documentation'
  - type: perf
    section: 'Performance improvements'
  - type: revert
    section: 'Bug Fixes'
  - type: test
    section: 'Tests'
  - type: ci
    section: 'Build and continuous integration'
  - type: build
    section: 'Build and continuous integration'
  - type: chore
    section: 'General maintenance'
  - type: style
    section: 'Style improvements'
  - type: refactor
    section: 'Refactoring'

_rules: &rules
  - type: chore
    release: patch
  - type: docs
    release: patch
  - type: revert
    release: patch
  - type: test
    release: patch

extends: 'semantic-release-monorepo'
branches:
  - main
  - name: beta
    prerelease: true
plugins:
  - [
      '@semantic-release/commit-analyzer',
      {preset: conventionalCommits, presetConfig: {types: *types}, releaseRules: *rules},
    ]
  - ['@semantic-release/release-notes-generator', {preset: conventionalCommits, presetConfig: {types: *types}}]
  - ['semantic-release-mirror-version', {fileGlob: 'meta.ts', placeholderRegExp: "(?<=@version\\s+)\\d+.\\d+.\\d+"}]
  - '@semantic-release/changelog'
  - ['@semantic-release/git', {assets: ['CHANGELOG.md']}]
  - ['@semantic-release/github', {assets: ['CHANGELOG.md', 'dist/*.user.js']}]
